# Generated by Django 5.1.7 on 2025-04-13 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthUsers",
            fields=[
                (
                    "id",
                    models.TextField(
                        default="USERID20250413100823759278",
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=50, unique=True)),
                ("email", models.EmailField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=50)),
                ("contact", models.CharField(max_length=12)),
                ("role", models.CharField(max_length=50)),
                ("status", models.BooleanField(default=True)),
                ("isActive", models.BooleanField(default=True)),
                ("isDeleted", models.BooleanField(default=False)),
                ("dateOfJoining", models.DateField()),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "createdBy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auths.authusers",
                    ),
                ),
            ],
        ),
    ]
