# Generated by Django 5.1.7 on 2025-04-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountuser",
            name="id",
            field=models.TextField(
                default="USERID20250413124311462099",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
