# Generated by Django 5.1.7 on 2025-04-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.TextField(
                        default="PATID20250413151727649029",
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("firstName", models.CharField(max_length=50)),
                ("lastName", models.CharField(max_length=50)),
                ("dob", models.DateField()),
                ("phone", models.CharField(max_length=15)),
                ("address", models.TextField()),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
