# Generated by Django 5.1.7 on 2025-04-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="id",
            field=models.TextField(
                default="PATID20250413100154304290",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
