# Generated by Django 5.1.7 on 2025-04-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0002_alter_patient_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="id",
            field=models.TextField(
                default="PATID20250413100823757673",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
