# Generated by Django 5.1.7 on 2025-04-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0003_alter_patient_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="id",
            field=models.TextField(
                default="PATID20250413123156330548",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
